from clint.textui import colored
import time
import os
def brute19banner():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████            --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████               --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████                 --V2.0--"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████"""+colored.red("          [")+colored.green("*")+colored.red("]")+colored.cyan("[Choose A Website]")))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████"""+colored.red("              [")+colored.green("1")+colored.red("]")+"Instagram"))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""+colored.red("              [")+colored.green("2")+colored.red("]")+"Facebook"))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""+colored.red("              [")+colored.green("3")+colored.red("]")+"Twitter"))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████"""))
def brute19bannertr():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████            --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████               --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████                 --V2.0--"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████"""+colored.red("          [")+colored.green("*")+colored.red("]")+colored.cyan("[Websitesi Seçiniz]")))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████"""+colored.red("              [")+colored.green("1")+colored.red("]")+"Instagram"))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""+colored.red("              [")+colored.green("2")+colored.red("]")+"Facebook"))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""+colored.red("              [")+colored.green("3")+colored.red("]")+"Twitter"))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████"""))
def normal_banner():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████            --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████               --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████                 --V2.0--"""))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████\n\n"""))

def bruter19_wordlist_banner():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████            --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████               --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████                 --V2.0--"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████"""+colored.red("          [")+colored.green("*")+colored.red("]")+colored.cyan("[Have You Generated A Wordlist?]")))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████"""+colored.red("              [")+colored.green("1")+colored.red("]")+"Yes(Use Your Own Wordlist)"))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""+colored.red("              [")+colored.green("2")+colored.red("]")+"No(Create A Personalized Wordlist)"))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████"""))
def bruter19_wordlist_banner_tr():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████                      --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████                         --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████                           --V2.0--"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████"""+colored.red("          [")+colored.green("*")+colored.red("]")+colored.cyan("[Daha Önceden Bir Wordlist Oluşturdunuz Mu?]")))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████"""+colored.red("              [")+colored.green("1")+colored.red("]")+"Evet(Kendine Ait Oluşturulmuş Wordlist'i Kullan)"))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""+colored.red("              [")+colored.green("2")+colored.red("]")+"Hayır(Kişiye Özel Bir Wordlist Oluştur)"))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████"""))
def bruter19_language():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████                  --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████                     --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████                       --V2.0--"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████"""+colored.red("          [")+colored.green("*")+colored.red("]")+colored.cyan("[Choose A Language / Dil Seçin]")))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████"""+colored.red("                     [")+colored.green("1")+colored.red("]")+"English"))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""+colored.red("                     [")+colored.green("2")+colored.red("]")+"Türkçe"))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████"""))